### ISSUE TITLE
Allow more levels in the ModelRegistry YAML configuration tree

### ISSUE THREAD

**Issue by Sheshuk** [SNEWS2/snewpy#269]
## What we have now
All models are listed in `models` section of the `model_files.yml`: https://github.com/SNEWS2/snewpy/blob/e0e47f500185fe71c801a6495d9526cad74e830c/python/snewpy/models/model_files.yml#L8-L14

That's ok for the ccsn case, but for adding the preSN models I would like to have them in a separate list. 

## What I suggest
Make a tree like
```yml
models: 
    ccsn:  
        Bollig_2016: 
            repository: *snewpy 
        Fornax_2019:  
            repository: *snewpy 
    presn:
        ...
```
and make the `_model_downloader` search not only by the model name, but also its module (`ccsn` or `presn`).

This will keep more order than just having all the models in one list.
